SELECT
    LEAGUE,
    SEASON,
    COUNT(*) AS CONCEDED_EVENTS,
    SUM(REACTED_FLAG) AS REACTED_EVENTS,
    ROUND(100.0 * SUM(REACTED_FLAG) / NULLIF(COUNT(*), 0), 2) AS PCT_REACTED,
    ROUND(AVG(GOALS_SCORED_AFTER_CONCEDING), 3) AS AVG_GOALS_AFTER_CONCEDING,
    SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) AS EVENTS_ENDED_WIN,
    SUM(IFF(FINAL_RESULT = 'DRAW', 1, 0)) AS EVENTS_ENDED_DRAW,
    SUM(IFF(FINAL_RESULT = 'LOSS', 1, 0)) AS EVENTS_ENDED_LOSS,
    ROUND(100.0 * SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) / NULLIF(COUNT(*), 0), 2) AS PCT_ENDED_WIN
FROM {{ ref('response_after_conceding') }}
GROUP BY LEAGUE, SEASON
