SELECT
    MATCH_ID,
    COMPETITION_NAME,
    ROUND,
    MATCH_DATE,
    MATCH_TIME,
    TEAM_HOME,
    TEAM_AWAY,
    GROUP_NAME,
    GROUND,
    SCORE_FT_HOME,
    SCORE_FT_AWAY,
    SCORE_HT_HOME,
    SCORE_HT_AWAY,
    SOURCE_FILE,
    INGESTED_AT,
    _RUN_ID
FROM {{ source('bronze', 'MATCHES') }}
