CREATE WAREHOUSE IF NOT EXISTS WH_DI_P_PIPELINE
    WITH
        WAREHOUSE_SIZE = 'XSMALL'
        AUTO_SUSPEND = 60
        AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE
        COMMENT = 'Warehouse do pipeline openfootball';

CREATE DATABASE IF NOT EXISTS DI_P_MEDALLION
    COMMENT = 'Database Medallion openfootball';

USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

CREATE SCHEMA IF NOT EXISTS BRONZE COMMENT = 'Bronze';
CREATE SCHEMA IF NOT EXISTS SILVER COMMENT = 'Silver';
CREATE SCHEMA IF NOT EXISTS GOLD COMMENT = 'Gold';
CREATE SCHEMA IF NOT EXISTS QC COMMENT = 'Quality checks';
CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Stage e formatos';
CREATE SCHEMA IF NOT EXISTS PIPE COMMENT = 'Procedures e tasks';

CREATE OR REPLACE FILE FORMAT RAW.FF_CSV_OPENFOOTBALL
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS RAW.STG_OPENFOOTBALL
    FILE_FORMAT = RAW.FF_CSV_OPENFOOTBALL
    COMMENT = 'Stage dos CSVs openfootball';

CREATE STAGE IF NOT EXISTS RAW.STG_SCRIPTS
    COMMENT = 'Stage dos scripts SQL do pipeline';

CREATE TABLE IF NOT EXISTS QC.PIPELINE_RUNS (
    RUN_ID STRING NOT NULL,
    STARTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    FINISHED_AT TIMESTAMP_NTZ,
    STATUS STRING,
    SOURCE_FILE STRING,
    BRONZE_ROWS NUMBER,
    SILVER_ROWS NUMBER,
    QUARANTINE_ROWS NUMBER,
    NOTES STRING
);

CREATE TABLE IF NOT EXISTS QC.CHECK_RESULTS (
    RUN_ID STRING,
    CHECK_ID STRING,
    CHECK_NAME STRING,
    LAYER STRING,
    STATUS STRING,
    FAILED_ROWS NUMBER,
    TOTAL_ROWS NUMBER,
    DETAILS STRING,
    CHECKED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS QC.PIPELINE_SCHEDULE (
    SCHEDULE_NAME STRING,
    CRON_EXPR STRING,
    TIMEZONE STRING,
    FREQUENCY_DESC STRING,
    JUSTIFICATION STRING,
    TASK_NAME STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS QC.DBT_RUN_RESULTS (
    INVOCATION_ID STRING,
    DBT_COMMAND STRING,
    UNIQUE_ID STRING,
    RESOURCE_TYPE STRING,
    NODE_NAME STRING,
    SCHEMA_NAME STRING,
    STATUS STRING,
    EXECUTION_TIME_SEC FLOAT,
    ROWS_AFFECTED NUMBER,
    MESSAGE STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
