USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

LIST @RAW.STG_OPENFOOTBALL;

CREATE OR REPLACE TEMPORARY TABLE RAW.RUN_CTX AS
SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

INSERT INTO QC.PIPELINE_RUNS (RUN_ID, STATUS, SOURCE_FILE, NOTES)
SELECT RUN_ID, 'RUNNING', 'data_flat/*.csv', 'Inicio Bronze MATCHES_RAW / GOALS_RAW'
FROM RAW.RUN_CTX;

CREATE OR REPLACE TABLE BRONZE.MATCHES_RAW (
    MATCH_ID STRING,
    SEASON STRING,
    LEAGUE_CODE STRING,
    LEAGUE_NAME STRING,
    MATCHDAY STRING,
    MATCH_DATE STRING,
    MATCH_TIME STRING,
    HOME_TEAM STRING,
    AWAY_TEAM STRING,
    HOME_SCORE_HT STRING,
    AWAY_SCORE_HT STRING,
    HOME_SCORE_FT STRING,
    AWAY_SCORE_FT STRING,
    SOURCE_FILE STRING,
    SOURCE_REPO STRING,
    HAS_GOAL_EVENTS STRING,
    _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _RUN_ID STRING
);

CREATE OR REPLACE TABLE BRONZE.GOALS_RAW (
    MATCH_ID STRING,
    SEASON STRING,
    LEAGUE_CODE STRING,
    LEAGUE_NAME STRING,
    MATCH_DATE STRING,
    MATCH_DATE_RAW STRING,
    HOME_TEAM STRING,
    AWAY_TEAM STRING,
    HOME_SCORE_FT STRING,
    AWAY_SCORE_FT STRING,
    TEAM STRING,
    OPPONENT STRING,
    SCORER STRING,
    MINUTE STRING,
    MINUTE_RAW STRING,
    IS_PENALTY STRING,
    IS_OWN_GOAL STRING,
    EVENT_SEQ STRING,
    SOURCE_FILE STRING,
    SOURCE_REPO STRING,
    _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _RUN_ID STRING
);

CREATE OR REPLACE TABLE BRONZE.LEAGUE_CATALOG (
    LEAGUE_CODE STRING,
    LEAGUE_NAME STRING,
    SEASON STRING,
    SOURCE_FILE STRING,
    _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _RUN_ID STRING
);

COPY INTO BRONZE.MATCHES_RAW (
    MATCH_ID, SEASON, LEAGUE_CODE, LEAGUE_NAME, MATCHDAY, MATCH_DATE, MATCH_TIME,
    HOME_TEAM, AWAY_TEAM, HOME_SCORE_HT, AWAY_SCORE_HT, HOME_SCORE_FT, AWAY_SCORE_FT,
    SOURCE_FILE, SOURCE_REPO, HAS_GOAL_EVENTS
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
    FROM @RAW.STG_OPENFOOTBALL/matches_bronze.csv
)
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_OPENFOOTBALL')
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.GOALS_RAW (
    MATCH_ID, SEASON, LEAGUE_CODE, LEAGUE_NAME, MATCH_DATE, MATCH_DATE_RAW,
    HOME_TEAM, AWAY_TEAM, HOME_SCORE_FT, AWAY_SCORE_FT,
    TEAM, OPPONENT, SCORER, MINUTE, MINUTE_RAW, IS_PENALTY, IS_OWN_GOAL, EVENT_SEQ,
    SOURCE_FILE, SOURCE_REPO
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
    FROM @RAW.STG_OPENFOOTBALL/goals_bronze.csv
)
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_OPENFOOTBALL')
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.LEAGUE_CATALOG (LEAGUE_CODE, LEAGUE_NAME, SEASON, SOURCE_FILE)
FROM (
    SELECT $1, $2, $3, $4
    FROM @RAW.STG_OPENFOOTBALL/league_catalog.csv
)
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_OPENFOOTBALL')
ON_ERROR = 'CONTINUE';

UPDATE BRONZE.MATCHES_RAW M
SET _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX)
WHERE _RUN_ID IS NULL;

UPDATE BRONZE.GOALS_RAW G
SET _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX)
WHERE _RUN_ID IS NULL;

UPDATE BRONZE.LEAGUE_CATALOG C
SET _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX)
WHERE _RUN_ID IS NULL;

UPDATE QC.PIPELINE_RUNS R
SET
    BRONZE_ROWS = (SELECT COUNT(*) FROM BRONZE.MATCHES_RAW),
    STATUS = 'BRONZE_OK',
    NOTES = 'MATCHES_RAW + GOALS_RAW carregados'
WHERE R.RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX);

SELECT 'MATCHES_RAW' AS T, COUNT(*) AS N FROM BRONZE.MATCHES_RAW
UNION ALL
SELECT 'GOALS_RAW', COUNT(*) FROM BRONZE.GOALS_RAW
UNION ALL
SELECT 'LEAGUE_CATALOG', COUNT(*) FROM BRONZE.LEAGUE_CATALOG;
