USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

LIST @RAW.STG_WORLDCUP;

CREATE OR REPLACE TEMPORARY TABLE RAW.RUN_CTX AS
SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

INSERT INTO QC.PIPELINE_RUNS (RUN_ID, STATUS, SOURCE_FILE, NOTES)
SELECT RUN_ID, 'RUNNING', 'data_flat/worldcup.json', 'Inicio Bronze MATCHES / GOALS_RAW'
FROM RAW.RUN_CTX;

-- BRONZE.MATCHES: carga full + MERGE (padrao Databricks)
CREATE OR REPLACE TEMPORARY TABLE RAW.MATCHES_STAGE (
    MATCH_ID STRING,
    COMPETITION_NAME STRING,
    ROUND STRING,
    MATCH_DATE STRING,
    MATCH_TIME STRING,
    TEAM_HOME STRING,
    TEAM_AWAY STRING,
    GROUP_NAME STRING,
    GROUND STRING,
    SCORE_FT_HOME STRING,
    SCORE_FT_AWAY STRING,
    SCORE_HT_HOME STRING,
    SCORE_HT_AWAY STRING,
    SOURCE_FILE STRING
);

COPY INTO RAW.MATCHES_STAGE
FROM @RAW.STG_WORLDCUP/matches_bronze.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_WORLDCUP')
ON_ERROR = 'CONTINUE';

CREATE TABLE IF NOT EXISTS BRONZE.MATCHES (
    MATCH_ID STRING,
    COMPETITION_NAME STRING,
    ROUND STRING,
    MATCH_DATE STRING,
    MATCH_TIME STRING,
    TEAM_HOME STRING,
    TEAM_AWAY STRING,
    GROUP_NAME STRING,
    GROUND STRING,
    SCORE_FT_HOME STRING,
    SCORE_FT_AWAY STRING,
    SCORE_HT_HOME STRING,
    SCORE_HT_AWAY STRING,
    SOURCE_FILE STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _RUN_ID STRING
);

MERGE INTO BRONZE.MATCHES T
USING RAW.MATCHES_STAGE S
ON T.MATCH_ID = S.MATCH_ID
WHEN MATCHED THEN UPDATE SET
    T.COMPETITION_NAME = S.COMPETITION_NAME,
    T.ROUND = S.ROUND,
    T.MATCH_DATE = S.MATCH_DATE,
    T.MATCH_TIME = S.MATCH_TIME,
    T.TEAM_HOME = S.TEAM_HOME,
    T.TEAM_AWAY = S.TEAM_AWAY,
    T.GROUP_NAME = S.GROUP_NAME,
    T.GROUND = S.GROUND,
    T.SCORE_FT_HOME = S.SCORE_FT_HOME,
    T.SCORE_FT_AWAY = S.SCORE_FT_AWAY,
    T.SCORE_HT_HOME = S.SCORE_HT_HOME,
    T.SCORE_HT_AWAY = S.SCORE_HT_AWAY,
    T.SOURCE_FILE = S.SOURCE_FILE,
    T.INGESTED_AT = CURRENT_TIMESTAMP(),
    T._RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX)
WHEN NOT MATCHED THEN INSERT (
    MATCH_ID, COMPETITION_NAME, ROUND, MATCH_DATE, MATCH_TIME,
    TEAM_HOME, TEAM_AWAY, GROUP_NAME, GROUND,
    SCORE_FT_HOME, SCORE_FT_AWAY, SCORE_HT_HOME, SCORE_HT_AWAY,
    SOURCE_FILE, INGESTED_AT, _RUN_ID
) VALUES (
    S.MATCH_ID, S.COMPETITION_NAME, S.ROUND, S.MATCH_DATE, S.MATCH_TIME,
    S.TEAM_HOME, S.TEAM_AWAY, S.GROUP_NAME, S.GROUND,
    S.SCORE_FT_HOME, S.SCORE_FT_AWAY, S.SCORE_HT_HOME, S.SCORE_HT_AWAY,
    S.SOURCE_FILE, CURRENT_TIMESTAMP(), (SELECT RUN_ID FROM RAW.RUN_CTX)
);

-- BRONZE.GOALS_RAW: overwrite completo (padrao Databricks)
CREATE OR REPLACE TABLE BRONZE.GOALS_RAW (
    MATCH_ID STRING,
    COMPETITION_NAME STRING,
    MATCH_DATE STRING,
    TEAM_HOME STRING,
    TEAM_AWAY STRING,
    SCORE_FT_HOME STRING,
    SCORE_FT_AWAY STRING,
    SOURCE_FILE STRING,
    TEAM STRING,
    OPPONENT STRING,
    SCORER STRING,
    MINUTE STRING,
    IS_PENALTY STRING,
    IS_OWN_GOAL STRING,
    EVENT_SEQ STRING,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _RUN_ID STRING
);

COPY INTO BRONZE.GOALS_RAW (
    MATCH_ID, COMPETITION_NAME, MATCH_DATE, TEAM_HOME, TEAM_AWAY,
    SCORE_FT_HOME, SCORE_FT_AWAY, SOURCE_FILE, TEAM, OPPONENT, SCORER,
    MINUTE, IS_PENALTY, IS_OWN_GOAL, EVENT_SEQ
)
FROM @RAW.STG_WORLDCUP/goals_bronze.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_WORLDCUP')
ON_ERROR = 'CONTINUE';

UPDATE BRONZE.GOALS_RAW
SET INGESTED_AT = CURRENT_TIMESTAMP(),
    _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX)
WHERE _RUN_ID IS NULL;

UPDATE QC.PIPELINE_RUNS R
SET BRONZE_ROWS = (SELECT COUNT(*) FROM BRONZE.MATCHES),
    STATUS = 'BRONZE_OK',
    NOTES = 'MATCHES (MERGE) + GOALS_RAW (overwrite)'
WHERE R.RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX);

SELECT 'BRONZE.MATCHES' AS T, COUNT(*) AS N FROM BRONZE.MATCHES
UNION ALL
SELECT 'BRONZE.GOALS_RAW', COUNT(*) FROM BRONZE.GOALS_RAW;
