USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

-- Silver matches: tipagem + quarantine de linhas invalidas
CREATE OR REPLACE TABLE SILVER.MATCHES_QUARANTINE AS
SELECT
    MATCH_ID,
    SEASON,
    LEAGUE_CODE,
    LEAGUE_NAME,
    MATCHDAY,
    MATCH_DATE,
    HOME_TEAM,
    AWAY_TEAM,
    HOME_SCORE_FT,
    AWAY_SCORE_FT,
    SOURCE_FILE,
    'INVALID_MATCH' AS QUARANTINE_REASON,
    CURRENT_TIMESTAMP() AS QUARANTINED_AT
FROM BRONZE.MATCHES_RAW
WHERE MATCH_ID IS NULL
   OR MATCH_DATE IS NULL
   OR HOME_TEAM IS NULL
   OR AWAY_TEAM IS NULL
   OR TRY_TO_NUMBER(HOME_SCORE_FT) IS NULL
   OR TRY_TO_NUMBER(AWAY_SCORE_FT) IS NULL
   OR TRY_TO_NUMBER(HOME_SCORE_FT) < 0
   OR TRY_TO_NUMBER(AWAY_SCORE_FT) < 0
   OR UPPER(TRIM(HOME_TEAM)) = UPPER(TRIM(AWAY_TEAM));

CREATE OR REPLACE TABLE SILVER.MATCHES AS
SELECT
    MATCH_ID,
    SEASON,
    LEAGUE_CODE,
    LEAGUE_NAME,
    MATCHDAY,
    TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE,
    MATCH_TIME,
    TRIM(HOME_TEAM) AS HOME_TEAM,
    TRIM(AWAY_TEAM) AS AWAY_TEAM,
    TRY_TO_NUMBER(HOME_SCORE_HT) AS HOME_SCORE_HT,
    TRY_TO_NUMBER(AWAY_SCORE_HT) AS AWAY_SCORE_HT,
    TRY_TO_NUMBER(HOME_SCORE_FT) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(AWAY_SCORE_FT) AS AWAY_SCORE_FT,
    SOURCE_FILE,
    SOURCE_REPO,
    TRY_TO_NUMBER(HAS_GOAL_EVENTS) AS HAS_GOAL_EVENTS,
    _INGESTED_AT,
    _RUN_ID
FROM BRONZE.MATCHES_RAW
WHERE MATCH_ID IS NOT NULL
  AND MATCH_DATE IS NOT NULL
  AND HOME_TEAM IS NOT NULL
  AND AWAY_TEAM IS NOT NULL
  AND TRY_TO_NUMBER(HOME_SCORE_FT) IS NOT NULL
  AND TRY_TO_NUMBER(AWAY_SCORE_FT) IS NOT NULL
  AND TRY_TO_NUMBER(HOME_SCORE_FT) >= 0
  AND TRY_TO_NUMBER(AWAY_SCORE_FT) >= 0
  AND UPPER(TRIM(HOME_TEAM)) <> UPPER(TRIM(AWAY_TEAM));

-- Eventos de gol: so competicoes com minuto (Copa)
CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS_QUARANTINE AS
SELECT
    MATCH_ID,
    TEAM,
    SCORER,
    MINUTE,
    IS_OWN_GOAL,
    'INVALID_GOAL_EVENT' AS QUARANTINE_REASON,
    CURRENT_TIMESTAMP() AS QUARANTINED_AT
FROM BRONZE.GOALS_RAW
WHERE MATCH_ID IS NULL
   OR TEAM IS NULL
   OR SCORER IS NULL
   OR TRY_TO_NUMBER(MINUTE) IS NULL
   OR TRY_TO_NUMBER(MINUTE) < 0
   OR TRY_TO_NUMBER(MINUTE) > 130;

CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS AS
SELECT
    G.MATCH_ID,
    G.SEASON,
    G.LEAGUE_CODE,
    G.LEAGUE_NAME,
    TRY_TO_DATE(G.MATCH_DATE) AS MATCH_DATE,
    TRIM(G.HOME_TEAM) AS HOME_TEAM,
    TRIM(G.AWAY_TEAM) AS AWAY_TEAM,
    TRY_TO_NUMBER(G.HOME_SCORE_FT) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(G.AWAY_SCORE_FT) AS AWAY_SCORE_FT,
    TRIM(G.TEAM) AS TEAM,
    TRIM(G.OPPONENT) AS OPPONENT,
    TRIM(G.SCORER) AS SCORER,
    TRY_TO_NUMBER(G.MINUTE)::NUMBER(38,0) AS MINUTE,
    G.MINUTE_RAW,
    TRY_TO_NUMBER(G.IS_PENALTY)::NUMBER(38,0) AS IS_PENALTY,
    TRY_TO_NUMBER(G.IS_OWN_GOAL)::NUMBER(38,0) AS IS_OWN_GOAL,
    TRY_TO_NUMBER(G.EVENT_SEQ)::NUMBER(38,0) AS EVENT_SEQ,
    -- time que recebe o credito do gol no placar
    CASE
        WHEN TRY_TO_NUMBER(G.IS_OWN_GOAL) = 1 THEN TRIM(G.OPPONENT)
        ELSE TRIM(G.TEAM)
    END AS CREDITED_TEAM,
    -- time que sofreu o gol
    CASE
        WHEN TRY_TO_NUMBER(G.IS_OWN_GOAL) = 1 THEN TRIM(G.TEAM)
        ELSE TRIM(G.OPPONENT)
    END AS CONCEDING_TEAM,
    G.SOURCE_FILE,
    G.SOURCE_REPO,
    G._INGESTED_AT,
    G._RUN_ID
FROM BRONZE.GOALS_RAW G
WHERE G.MATCH_ID IS NOT NULL
  AND G.TEAM IS NOT NULL
  AND G.SCORER IS NOT NULL
  AND TRY_TO_NUMBER(G.MINUTE) IS NOT NULL
  AND TRY_TO_NUMBER(G.MINUTE) >= 0
  AND TRY_TO_NUMBER(G.MINUTE) <= 130;

SELECT 'SILVER.MATCHES' AS T, COUNT(*) AS N FROM SILVER.MATCHES
UNION ALL
SELECT 'SILVER.GOAL_EVENTS', COUNT(*) FROM SILVER.GOAL_EVENTS
UNION ALL
SELECT 'SILVER.MATCHES_QUARANTINE', COUNT(*) FROM SILVER.MATCHES_QUARANTINE
UNION ALL
SELECT 'SILVER.GOAL_EVENTS_QUARANTINE', COUNT(*) FROM SILVER.GOAL_EVENTS_QUARANTINE;
