USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

-- Silver matches: tipagem + quarantine (PARTIDA_INVALIDA)
CREATE OR REPLACE TABLE SILVER.MATCHES_QUARANTINE AS
SELECT
    MATCH_ID,
    COMPETITION_NAME,
    ROUND,
    MATCH_DATE,
    MATCH_TIME,
    TEAM_HOME,
    TEAM_AWAY,
    SCORE_FT_HOME,
    SCORE_FT_AWAY,
    SOURCE_FILE,
    'PARTIDA_INVALIDA' AS QUARANTINE_REASON,
    CURRENT_TIMESTAMP() AS QUARANTINED_AT
FROM BRONZE.MATCHES
WHERE MATCH_ID IS NULL
   OR MATCH_DATE IS NULL
   OR TEAM_HOME IS NULL
   OR TEAM_AWAY IS NULL
   OR TRY_TO_NUMBER(SCORE_FT_HOME) IS NULL
   OR TRY_TO_NUMBER(SCORE_FT_AWAY) IS NULL
   OR TRY_TO_NUMBER(SCORE_FT_HOME) < 0
   OR TRY_TO_NUMBER(SCORE_FT_AWAY) < 0
   OR UPPER(TRIM(TEAM_HOME)) = UPPER(TRIM(TEAM_AWAY));

CREATE OR REPLACE TABLE SILVER.MATCHES AS
SELECT
    MATCH_ID,
    COMPETITION_NAME,
    ROUND AS MATCHDAY,
    TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE,
    MATCH_TIME,
    TRIM(TEAM_HOME) AS HOME_TEAM,
    TRIM(TEAM_AWAY) AS AWAY_TEAM,
    TRY_TO_NUMBER(SCORE_HT_HOME) AS HOME_SCORE_HT,
    TRY_TO_NUMBER(SCORE_HT_AWAY) AS AWAY_SCORE_HT,
    TRY_TO_NUMBER(SCORE_FT_HOME) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(SCORE_FT_AWAY) AS AWAY_SCORE_FT,
    SOURCE_FILE,
    INGESTED_AT
FROM BRONZE.MATCHES
WHERE MATCH_ID IS NOT NULL
  AND MATCH_DATE IS NOT NULL
  AND TEAM_HOME IS NOT NULL
  AND TEAM_AWAY IS NOT NULL
  AND TRY_TO_NUMBER(SCORE_FT_HOME) IS NOT NULL
  AND TRY_TO_NUMBER(SCORE_FT_AWAY) IS NOT NULL
  AND TRY_TO_NUMBER(SCORE_FT_HOME) >= 0
  AND TRY_TO_NUMBER(SCORE_FT_AWAY) >= 0
  AND UPPER(TRIM(TEAM_HOME)) <> UPPER(TRIM(TEAM_AWAY));

-- Goal events quarantine (EVENTO_GOL_INVALIDO)
CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS_QUARANTINE AS
SELECT
    MATCH_ID,
    COMPETITION_NAME,
    MATCH_DATE,
    TEAM_HOME,
    TEAM_AWAY,
    TEAM,
    OPPONENT,
    SCORER,
    MINUTE,
    SOURCE_FILE,
    'EVENTO_GOL_INVALIDO' AS QUARANTINE_REASON,
    CURRENT_TIMESTAMP() AS QUARANTINED_AT
FROM BRONZE.GOALS_RAW
WHERE MATCH_ID IS NULL
   OR TEAM IS NULL
   OR SCORER IS NULL
   OR TRY_TO_NUMBER(MINUTE) IS NULL
   OR TRY_TO_NUMBER(MINUTE) < 0
   OR TRY_TO_NUMBER(MINUTE) > 130;

-- credited_team / conceding_team: igual Databricks (API ja credita no placar)
CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS AS
SELECT
    G.MATCH_ID,
    G.COMPETITION_NAME,
    TRY_TO_DATE(G.MATCH_DATE) AS MATCH_DATE,
    TRIM(G.TEAM_HOME) AS HOME_TEAM,
    TRIM(G.TEAM_AWAY) AS AWAY_TEAM,
    TRY_TO_NUMBER(G.SCORE_FT_HOME) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(G.SCORE_FT_AWAY) AS AWAY_SCORE_FT,
    TRIM(G.TEAM) AS TEAM,
    TRIM(G.OPPONENT) AS OPPONENT,
    TRIM(G.SCORER) AS SCORER,
    TRY_TO_NUMBER(G.MINUTE)::NUMBER(38, 0) AS MINUTE,
    TRY_TO_NUMBER(G.IS_PENALTY)::NUMBER(38, 0) AS IS_PENALTY,
    TRY_TO_NUMBER(G.IS_OWN_GOAL)::NUMBER(38, 0) AS IS_OWN_GOAL,
    TRY_TO_NUMBER(G.EVENT_SEQ)::NUMBER(38, 0) AS EVENT_SEQ,
    TRIM(G.TEAM) AS CREDITED_TEAM,
    TRIM(G.OPPONENT) AS CONCEDING_TEAM,
    G.SOURCE_FILE,
    G.INGESTED_AT
FROM BRONZE.GOALS_RAW G
WHERE G.MATCH_ID IS NOT NULL
  AND G.TEAM IS NOT NULL
  AND G.SCORER IS NOT NULL
  AND TRY_TO_NUMBER(G.MINUTE) IS NOT NULL
  AND TRY_TO_NUMBER(G.MINUTE) >= 0
  AND TRY_TO_NUMBER(G.MINUTE) <= 130;

SELECT 'SILVER.MATCHES' AS T, COUNT(*) AS N FROM SILVER.MATCHES
UNION ALL
SELECT 'SILVER.GOAL_EVENTS', COUNT(*) FROM SILVER.GOAL_EVENTS
UNION ALL
SELECT 'SILVER.MATCHES_QUARANTINE', COUNT(*) FROM SILVER.MATCHES_QUARANTINE
UNION ALL
SELECT 'SILVER.GOAL_EVENTS_QUARANTINE', COUNT(*) FROM SILVER.GOAL_EVENTS_QUARANTINE;
