USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

-- Gold alinhado ao Databricks: fact_reaction_events + dim_competition_summary
CREATE OR REPLACE TABLE GOLD.FACT_REACTION_EVENTS AS
WITH ordered AS (
    SELECT
        E.MATCH_ID,
        E.COMPETITION_NAME,
        E.MATCH_DATE,
        E.HOME_TEAM,
        E.AWAY_TEAM,
        E.HOME_SCORE_FT,
        E.AWAY_SCORE_FT,
        E.SCORER,
        E.MINUTE AS GOAL_MINUTE,
        E.EVENT_SEQ,
        E.IS_PENALTY,
        E.IS_OWN_GOAL,
        E.CREDITED_TEAM,
        E.CONCEDING_TEAM
    FROM SILVER.GOAL_EVENTS E
),
scored AS (
    SELECT
        O.*,
        (
            SELECT COUNT(*)
            FROM ordered P
            WHERE P.MATCH_ID = O.MATCH_ID
              AND (
                    P.GOAL_MINUTE < O.GOAL_MINUTE
                    OR (P.GOAL_MINUTE = O.GOAL_MINUTE AND P.EVENT_SEQ < O.EVENT_SEQ)
              )
              AND P.CREDITED_TEAM = O.HOME_TEAM
        ) AS HOME_GOALS_BEFORE,
        (
            SELECT COUNT(*)
            FROM ordered P
            WHERE P.MATCH_ID = O.MATCH_ID
              AND (
                    P.GOAL_MINUTE < O.GOAL_MINUTE
                    OR (P.GOAL_MINUTE = O.GOAL_MINUTE AND P.EVENT_SEQ < O.EVENT_SEQ)
              )
              AND P.CREDITED_TEAM = O.AWAY_TEAM
        ) AS AWAY_GOALS_BEFORE,
        (
            SELECT COUNT(*)
            FROM ordered AFT
            WHERE AFT.MATCH_ID = O.MATCH_ID
              AND AFT.CREDITED_TEAM = O.CONCEDING_TEAM
              AND (
                    AFT.GOAL_MINUTE > O.GOAL_MINUTE
                    OR (AFT.GOAL_MINUTE = O.GOAL_MINUTE AND AFT.EVENT_SEQ > O.EVENT_SEQ)
              )
        ) AS GOALS_SCORED_AFTER_CONCEDING
    FROM ordered O
)
SELECT
    MATCH_ID,
    COMPETITION_NAME,
    MATCH_DATE,
    HOME_TEAM,
    AWAY_TEAM,
    CONCEDING_TEAM,
    CREDITED_TEAM AS SCORING_TEAM,
    SCORER,
    GOAL_MINUTE,
    EVENT_SEQ,
    IS_PENALTY,
    IS_OWN_GOAL,
    CASE
        WHEN CONCEDING_TEAM = HOME_TEAM THEN HOME_GOALS_BEFORE - AWAY_GOALS_BEFORE
        ELSE AWAY_GOALS_BEFORE - HOME_GOALS_BEFORE
    END AS SCORE_DIFF_BEFORE_GOAL,
    GOALS_SCORED_AFTER_CONCEDING,
    CASE
        WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT > AWAY_SCORE_FT THEN 'WIN'
        WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT = AWAY_SCORE_FT THEN 'DRAW'
        WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT < AWAY_SCORE_FT THEN 'LOSS'
        WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT > HOME_SCORE_FT THEN 'WIN'
        WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT = HOME_SCORE_FT THEN 'DRAW'
        WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT < HOME_SCORE_FT THEN 'LOSS'
        ELSE 'UNKNOWN'
    END AS FINAL_RESULT,
    IFF(GOALS_SCORED_AFTER_CONCEDING > 0, 1, 0) AS REACTED_FLAG,
    CURRENT_TIMESTAMP() AS BUILT_AT
FROM scored;

CREATE OR REPLACE TABLE GOLD.DIM_COMPETITION_SUMMARY AS
SELECT
    COMPETITION_NAME,
    COUNT(*) AS CONCEDED_EVENTS,
    SUM(REACTED_FLAG) AS REACTED_EVENTS,
    ROUND(100.0 * SUM(REACTED_FLAG) / NULLIF(COUNT(*), 0), 2) AS PCT_REACTED,
    ROUND(AVG(GOALS_SCORED_AFTER_CONCEDING), 3) AS AVG_GOALS_AFTER_CONCEDING,
    SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) AS EVENTS_ENDED_WIN,
    SUM(IFF(FINAL_RESULT = 'DRAW', 1, 0)) AS EVENTS_ENDED_DRAW,
    SUM(IFF(FINAL_RESULT = 'LOSS', 1, 0)) AS EVENTS_ENDED_LOSS,
    ROUND(100.0 * SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) / NULLIF(COUNT(*), 0), 2) AS PCT_ENDED_WIN,
    CURRENT_TIMESTAMP() AS BUILT_AT
FROM GOLD.FACT_REACTION_EVENTS
GROUP BY COMPETITION_NAME
ORDER BY COMPETITION_NAME;

SELECT 'GOLD.FACT_REACTION_EVENTS' AS T, COUNT(*) AS N FROM GOLD.FACT_REACTION_EVENTS
UNION ALL
SELECT 'GOLD.DIM_COMPETITION_SUMMARY', COUNT(*) FROM GOLD.DIM_COMPETITION_SUMMARY;

SELECT * FROM GOLD.DIM_COMPETITION_SUMMARY ORDER BY COMPETITION_NAME;
