USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

CREATE OR REPLACE TEMPORARY TABLE RAW.QC_RUN_CTX AS
SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC01',
    'matches_required_fields',
    'BRONZE',
    IFF(SUM(IFF(
        MATCH_DATE IS NULL OR TEAM_HOME IS NULL OR TEAM_AWAY IS NULL
        OR SCORE_FT_HOME IS NULL OR SCORE_FT_AWAY IS NULL, 1, 0
    )) = 0, 'PASS', 'FAIL'),
    SUM(IFF(
        MATCH_DATE IS NULL OR TEAM_HOME IS NULL OR TEAM_AWAY IS NULL
        OR SCORE_FT_HOME IS NULL OR SCORE_FT_AWAY IS NULL, 1, 0
    )),
    COUNT(*),
    'date/teams/score obrigatorios'
FROM BRONZE.MATCHES;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC02',
    'matches_score_non_negative',
    'BRONZE',
    IFF(SUM(IFF(TRY_TO_NUMBER(SCORE_FT_HOME) < 0 OR TRY_TO_NUMBER(SCORE_FT_AWAY) < 0, 1, 0)) = 0, 'PASS', 'FAIL'),
    SUM(IFF(TRY_TO_NUMBER(SCORE_FT_HOME) < 0 OR TRY_TO_NUMBER(SCORE_FT_AWAY) < 0, 1, 0)),
    COUNT(*),
    'score >= 0'
FROM BRONZE.MATCHES;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC03',
    'goal_events_fk_matches',
    'SILVER',
    IFF(SUM(IFF(M.MATCH_ID IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
    SUM(IFF(M.MATCH_ID IS NULL, 1, 0)),
    COUNT(*),
    'goal_events.match_id em silver.matches'
FROM SILVER.GOAL_EVENTS G
LEFT JOIN SILVER.MATCHES M ON G.MATCH_ID = M.MATCH_ID;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC04',
    'goal_minute_range',
    'SILVER',
    IFF(SUM(IFF(MINUTE < 0 OR MINUTE > 130, 1, 0)) = 0, 'PASS', 'FAIL'),
    SUM(IFF(MINUTE < 0 OR MINUTE > 130, 1, 0)),
    COUNT(*),
    'minuto entre 0 e 130'
FROM SILVER.GOAL_EVENTS;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC05',
    'fact_reacted_flag_consistency',
    'GOLD',
    IFF(SUM(IFF(
        (GOALS_SCORED_AFTER_CONCEDING > 0 AND REACTED_FLAG <> 1)
        OR (GOALS_SCORED_AFTER_CONCEDING = 0 AND REACTED_FLAG <> 0), 1, 0
    )) = 0, 'PASS', 'FAIL'),
    SUM(IFF(
        (GOALS_SCORED_AFTER_CONCEDING > 0 AND REACTED_FLAG <> 1)
        OR (GOALS_SCORED_AFTER_CONCEDING = 0 AND REACTED_FLAG <> 0), 1, 0
    )),
    COUNT(*),
    'reacted_flag coerente com goals_after'
FROM GOLD.FACT_REACTION_EVENTS;

SELECT CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS
FROM QC.CHECK_RESULTS
WHERE RUN_ID = (SELECT RUN_ID FROM RAW.QC_RUN_CTX)
ORDER BY CHECK_ID;
