USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;

CREATE OR REPLACE TEMPORARY TABLE RAW.QC_RUN_CTX AS
SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

-- QC Bronze: campos obrigatorios / score >= 0
INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC01',
    'matches_required_fields',
    'BRONZE',
    IFF(SUM(IFF(
        MATCH_DATE IS NULL OR HOME_TEAM IS NULL OR AWAY_TEAM IS NULL
        OR HOME_SCORE_FT IS NULL OR AWAY_SCORE_FT IS NULL, 1, 0
    )) = 0, 'PASS', 'FAIL'),
    SUM(IFF(
        MATCH_DATE IS NULL OR HOME_TEAM IS NULL OR AWAY_TEAM IS NULL
        OR HOME_SCORE_FT IS NULL OR AWAY_SCORE_FT IS NULL, 1, 0
    )),
    COUNT(*),
    'date/team1/team2/score obrigatorios'
FROM BRONZE.MATCHES_RAW;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC02',
    'matches_score_non_negative',
    'BRONZE',
    IFF(SUM(IFF(TRY_TO_NUMBER(HOME_SCORE_FT) < 0 OR TRY_TO_NUMBER(AWAY_SCORE_FT) < 0, 1, 0)) = 0, 'PASS', 'FAIL'),
    SUM(IFF(TRY_TO_NUMBER(HOME_SCORE_FT) < 0 OR TRY_TO_NUMBER(AWAY_SCORE_FT) < 0, 1, 0)),
    COUNT(*),
    'score >= 0'
FROM BRONZE.MATCHES_RAW;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC03',
    'goal_event_has_valid_match_id',
    'SILVER',
    IFF(SUM(IFF(M.MATCH_ID IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
    SUM(IFF(M.MATCH_ID IS NULL, 1, 0)),
    COUNT(*),
    'goal_event.match_id existe em SILVER.MATCHES'
FROM SILVER.GOAL_EVENTS G
LEFT JOIN SILVER.MATCHES M ON G.MATCH_ID = M.MATCH_ID;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC04',
    'matches_unique_natural_key',
    'SILVER',
    IFF(COUNT(*) = COUNT(DISTINCT MATCH_ID), 'PASS', 'FAIL'),
    COUNT(*) - COUNT(DISTINCT MATCH_ID),
    COUNT(*),
    'match_id unico'
FROM SILVER.MATCHES;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC05',
    'goal_events_minute_sane',
    'SILVER',
    IFF(SUM(IFF(MINUTE < 0 OR MINUTE > 130 OR SCORER IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
    SUM(IFF(MINUTE < 0 OR MINUTE > 130 OR SCORER IS NULL, 1, 0)),
    COUNT(*),
    'minute 0-130 e scorer not null'
FROM SILVER.GOAL_EVENTS;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC06',
    'gold_has_reaction_rows',
    'GOLD',
    IFF(COUNT(*) > 0, 'PASS', 'FAIL'),
    IFF(COUNT(*) > 0, 0, 1),
    COUNT(*),
    'RESPONSE_AFTER_CONCEDING populada'
FROM GOLD.RESPONSE_AFTER_CONCEDING;

INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
SELECT
    (SELECT RUN_ID FROM RAW.QC_RUN_CTX),
    'QC07',
    'gold_no_unknown_final_result',
    'GOLD',
    IFF(SUM(IFF(FINAL_RESULT = 'UNKNOWN', 1, 0)) = 0, 'PASS', 'FAIL'),
    SUM(IFF(FINAL_RESULT = 'UNKNOWN', 1, 0)),
    COUNT(*),
    'final_result conhecido'
FROM GOLD.RESPONSE_AFTER_CONCEDING;

SELECT * FROM QC.CHECK_RESULTS
WHERE RUN_ID = (SELECT RUN_ID FROM RAW.QC_RUN_CTX)
ORDER BY CHECK_ID;
