USE ROLE ACCOUNTADMIN;
USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;
USE SCHEMA PIPE;

CREATE SCHEMA IF NOT EXISTS PIPE COMMENT = 'Procedures e tasks do pipeline';

CREATE OR REPLACE PROCEDURE PIPE.SP_BRONZE_INGEST()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE RAW.RUN_CTX AS
    SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

    INSERT INTO QC.PIPELINE_RUNS (RUN_ID, STATUS, SOURCE_FILE, NOTES)
    SELECT RUN_ID, 'RUNNING', 'stage:@RAW.STG_WORLDCUP', 'Inicio Bronze MATCHES/GOALS_RAW'
    FROM RAW.RUN_CTX;

    CREATE OR REPLACE TEMPORARY TABLE RAW.MATCHES_STAGE (
        MATCH_ID STRING, COMPETITION_NAME STRING, ROUND STRING, MATCH_DATE STRING, MATCH_TIME STRING,
        TEAM_HOME STRING, TEAM_AWAY STRING, GROUP_NAME STRING, GROUND STRING,
        SCORE_FT_HOME STRING, SCORE_FT_AWAY STRING, SCORE_HT_HOME STRING, SCORE_HT_AWAY STRING,
        SOURCE_FILE STRING
    );

    COPY INTO RAW.MATCHES_STAGE
    FROM @RAW.STG_WORLDCUP/matches_bronze.csv
    FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_WORLDCUP')
    ON_ERROR = 'CONTINUE';

    CREATE TABLE IF NOT EXISTS BRONZE.MATCHES (
        MATCH_ID STRING, COMPETITION_NAME STRING, ROUND STRING, MATCH_DATE STRING, MATCH_TIME STRING,
        TEAM_HOME STRING, TEAM_AWAY STRING, GROUP_NAME STRING, GROUND STRING,
        SCORE_FT_HOME STRING, SCORE_FT_AWAY STRING, SCORE_HT_HOME STRING, SCORE_HT_AWAY STRING,
        SOURCE_FILE STRING, INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _RUN_ID STRING
    );

    MERGE INTO BRONZE.MATCHES T
    USING RAW.MATCHES_STAGE S
    ON T.MATCH_ID = S.MATCH_ID
    WHEN MATCHED THEN UPDATE SET
        T.COMPETITION_NAME = S.COMPETITION_NAME, T.ROUND = S.ROUND, T.MATCH_DATE = S.MATCH_DATE,
        T.MATCH_TIME = S.MATCH_TIME, T.TEAM_HOME = S.TEAM_HOME, T.TEAM_AWAY = S.TEAM_AWAY,
        T.GROUP_NAME = S.GROUP_NAME, T.GROUND = S.GROUND,
        T.SCORE_FT_HOME = S.SCORE_FT_HOME, T.SCORE_FT_AWAY = S.SCORE_FT_AWAY,
        T.SCORE_HT_HOME = S.SCORE_HT_HOME, T.SCORE_HT_AWAY = S.SCORE_HT_AWAY,
        T.SOURCE_FILE = S.SOURCE_FILE, T.INGESTED_AT = CURRENT_TIMESTAMP(),
        T._RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX)
    WHEN NOT MATCHED THEN INSERT (
        MATCH_ID, COMPETITION_NAME, ROUND, MATCH_DATE, MATCH_TIME, TEAM_HOME, TEAM_AWAY,
        GROUP_NAME, GROUND, SCORE_FT_HOME, SCORE_FT_AWAY, SCORE_HT_HOME, SCORE_HT_AWAY,
        SOURCE_FILE, INGESTED_AT, _RUN_ID
    ) VALUES (
        S.MATCH_ID, S.COMPETITION_NAME, S.ROUND, S.MATCH_DATE, S.MATCH_TIME, S.TEAM_HOME, S.TEAM_AWAY,
        S.GROUP_NAME, S.GROUND, S.SCORE_FT_HOME, S.SCORE_FT_AWAY, S.SCORE_HT_HOME, S.SCORE_HT_AWAY,
        S.SOURCE_FILE, CURRENT_TIMESTAMP(), (SELECT RUN_ID FROM RAW.RUN_CTX)
    );

    CREATE OR REPLACE TABLE BRONZE.GOALS_RAW (
        MATCH_ID STRING, COMPETITION_NAME STRING, MATCH_DATE STRING, TEAM_HOME STRING, TEAM_AWAY STRING,
        SCORE_FT_HOME STRING, SCORE_FT_AWAY STRING, SOURCE_FILE STRING, TEAM STRING, OPPONENT STRING,
        SCORER STRING, MINUTE STRING, IS_PENALTY STRING, IS_OWN_GOAL STRING, EVENT_SEQ STRING,
        INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _RUN_ID STRING
    );

    COPY INTO BRONZE.GOALS_RAW (
        MATCH_ID, COMPETITION_NAME, MATCH_DATE, TEAM_HOME, TEAM_AWAY, SCORE_FT_HOME, SCORE_FT_AWAY,
        SOURCE_FILE, TEAM, OPPONENT, SCORER, MINUTE, IS_PENALTY, IS_OWN_GOAL, EVENT_SEQ
    )
    FROM @RAW.STG_WORLDCUP/goals_bronze.csv
    FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_WORLDCUP')
    ON_ERROR = 'CONTINUE';

    UPDATE BRONZE.GOALS_RAW
    SET INGESTED_AT = CURRENT_TIMESTAMP(), _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX)
    WHERE _RUN_ID IS NULL;

    UPDATE QC.PIPELINE_RUNS R
    SET BRONZE_ROWS = (SELECT COUNT(*) FROM BRONZE.MATCHES),
        STATUS = 'BRONZE_OK',
        NOTES = 'MATCHES MERGE + GOALS_RAW overwrite'
    WHERE R.RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX);

    RETURN 'BRONZE_OK matches=' || (SELECT COUNT(*)::STRING FROM BRONZE.MATCHES)
        || ' goals=' || (SELECT COUNT(*)::STRING FROM BRONZE.GOALS_RAW);
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_SILVER_TRANSFORM()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TABLE SILVER.MATCHES_QUARANTINE AS
    SELECT MATCH_ID, COMPETITION_NAME, ROUND, MATCH_DATE, MATCH_TIME, TEAM_HOME, TEAM_AWAY,
           SCORE_FT_HOME, SCORE_FT_AWAY, SOURCE_FILE,
           'PARTIDA_INVALIDA' AS QUARANTINE_REASON, CURRENT_TIMESTAMP() AS QUARANTINED_AT
    FROM BRONZE.MATCHES
    WHERE MATCH_ID IS NULL OR MATCH_DATE IS NULL OR TEAM_HOME IS NULL OR TEAM_AWAY IS NULL
       OR TRY_TO_NUMBER(SCORE_FT_HOME) IS NULL OR TRY_TO_NUMBER(SCORE_FT_AWAY) IS NULL
       OR TRY_TO_NUMBER(SCORE_FT_HOME) < 0 OR TRY_TO_NUMBER(SCORE_FT_AWAY) < 0
       OR UPPER(TRIM(TEAM_HOME)) = UPPER(TRIM(TEAM_AWAY));

    CREATE OR REPLACE TABLE SILVER.MATCHES AS
    SELECT MATCH_ID, COMPETITION_NAME, ROUND AS MATCHDAY, TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE,
           MATCH_TIME, TRIM(TEAM_HOME) AS HOME_TEAM, TRIM(TEAM_AWAY) AS AWAY_TEAM,
           TRY_TO_NUMBER(SCORE_HT_HOME) AS HOME_SCORE_HT, TRY_TO_NUMBER(SCORE_HT_AWAY) AS AWAY_SCORE_HT,
           TRY_TO_NUMBER(SCORE_FT_HOME) AS HOME_SCORE_FT, TRY_TO_NUMBER(SCORE_FT_AWAY) AS AWAY_SCORE_FT,
           SOURCE_FILE, INGESTED_AT
    FROM BRONZE.MATCHES
    WHERE MATCH_ID IS NOT NULL AND MATCH_DATE IS NOT NULL AND TEAM_HOME IS NOT NULL AND TEAM_AWAY IS NOT NULL
      AND TRY_TO_NUMBER(SCORE_FT_HOME) IS NOT NULL AND TRY_TO_NUMBER(SCORE_FT_AWAY) IS NOT NULL
      AND TRY_TO_NUMBER(SCORE_FT_HOME) >= 0 AND TRY_TO_NUMBER(SCORE_FT_AWAY) >= 0
      AND UPPER(TRIM(TEAM_HOME)) <> UPPER(TRIM(TEAM_AWAY));

    CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS_QUARANTINE AS
    SELECT MATCH_ID, COMPETITION_NAME, MATCH_DATE, TEAM_HOME, TEAM_AWAY, TEAM, OPPONENT, SCORER, MINUTE,
           SOURCE_FILE, 'EVENTO_GOL_INVALIDO' AS QUARANTINE_REASON, CURRENT_TIMESTAMP() AS QUARANTINED_AT
    FROM BRONZE.GOALS_RAW
    WHERE MATCH_ID IS NULL OR TEAM IS NULL OR SCORER IS NULL
       OR TRY_TO_NUMBER(MINUTE) IS NULL OR TRY_TO_NUMBER(MINUTE) < 0 OR TRY_TO_NUMBER(MINUTE) > 130;

    CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS AS
    SELECT G.MATCH_ID, G.COMPETITION_NAME, TRY_TO_DATE(G.MATCH_DATE) AS MATCH_DATE,
           TRIM(G.TEAM_HOME) AS HOME_TEAM, TRIM(G.TEAM_AWAY) AS AWAY_TEAM,
           TRY_TO_NUMBER(G.SCORE_FT_HOME) AS HOME_SCORE_FT, TRY_TO_NUMBER(G.SCORE_FT_AWAY) AS AWAY_SCORE_FT,
           TRIM(G.TEAM) AS TEAM, TRIM(G.OPPONENT) AS OPPONENT, TRIM(G.SCORER) AS SCORER,
           TRY_TO_NUMBER(G.MINUTE)::NUMBER(38,0) AS MINUTE,
           TRY_TO_NUMBER(G.IS_PENALTY)::NUMBER(38,0) AS IS_PENALTY,
           TRY_TO_NUMBER(G.IS_OWN_GOAL)::NUMBER(38,0) AS IS_OWN_GOAL,
           TRY_TO_NUMBER(G.EVENT_SEQ)::NUMBER(38,0) AS EVENT_SEQ,
           TRIM(G.TEAM) AS CREDITED_TEAM,
           TRIM(G.OPPONENT) AS CONCEDING_TEAM,
           G.SOURCE_FILE, G.INGESTED_AT
    FROM BRONZE.GOALS_RAW G
    WHERE G.MATCH_ID IS NOT NULL AND G.TEAM IS NOT NULL AND G.SCORER IS NOT NULL
      AND TRY_TO_NUMBER(G.MINUTE) IS NOT NULL
      AND TRY_TO_NUMBER(G.MINUTE) >= 0 AND TRY_TO_NUMBER(G.MINUTE) <= 130;

    RETURN 'SILVER_OK matches=' || (SELECT COUNT(*)::STRING FROM SILVER.MATCHES)
        || ' goals=' || (SELECT COUNT(*)::STRING FROM SILVER.GOAL_EVENTS);
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_GOLD_BUILD()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TABLE GOLD.FACT_REACTION_EVENTS AS
    WITH ordered AS (
        SELECT E.MATCH_ID, E.COMPETITION_NAME, E.MATCH_DATE, E.HOME_TEAM, E.AWAY_TEAM,
               E.HOME_SCORE_FT, E.AWAY_SCORE_FT, E.SCORER, E.MINUTE AS GOAL_MINUTE, E.EVENT_SEQ,
               E.IS_PENALTY, E.IS_OWN_GOAL, E.CREDITED_TEAM, E.CONCEDING_TEAM
        FROM SILVER.GOAL_EVENTS E
    ),
    scored AS (
        SELECT O.*,
            (SELECT COUNT(*) FROM ordered P
             WHERE P.MATCH_ID = O.MATCH_ID
               AND (P.GOAL_MINUTE < O.GOAL_MINUTE
                    OR (P.GOAL_MINUTE = O.GOAL_MINUTE AND P.EVENT_SEQ < O.EVENT_SEQ))
               AND P.CREDITED_TEAM = O.HOME_TEAM) AS HOME_GOALS_BEFORE,
            (SELECT COUNT(*) FROM ordered P
             WHERE P.MATCH_ID = O.MATCH_ID
               AND (P.GOAL_MINUTE < O.GOAL_MINUTE
                    OR (P.GOAL_MINUTE = O.GOAL_MINUTE AND P.EVENT_SEQ < O.EVENT_SEQ))
               AND P.CREDITED_TEAM = O.AWAY_TEAM) AS AWAY_GOALS_BEFORE,
            (SELECT COUNT(*) FROM ordered AFT
             WHERE AFT.MATCH_ID = O.MATCH_ID
               AND AFT.CREDITED_TEAM = O.CONCEDING_TEAM
               AND (AFT.GOAL_MINUTE > O.GOAL_MINUTE
                    OR (AFT.GOAL_MINUTE = O.GOAL_MINUTE AND AFT.EVENT_SEQ > O.EVENT_SEQ))
            ) AS GOALS_SCORED_AFTER_CONCEDING
        FROM ordered O
    )
    SELECT MATCH_ID, COMPETITION_NAME, MATCH_DATE, HOME_TEAM, AWAY_TEAM,
        CONCEDING_TEAM, CREDITED_TEAM AS SCORING_TEAM, SCORER, GOAL_MINUTE, EVENT_SEQ,
        IS_PENALTY, IS_OWN_GOAL,
        CASE WHEN CONCEDING_TEAM = HOME_TEAM THEN HOME_GOALS_BEFORE - AWAY_GOALS_BEFORE
             ELSE AWAY_GOALS_BEFORE - HOME_GOALS_BEFORE END AS SCORE_DIFF_BEFORE_GOAL,
        GOALS_SCORED_AFTER_CONCEDING,
        CASE
            WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT > AWAY_SCORE_FT THEN 'WIN'
            WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT = AWAY_SCORE_FT THEN 'DRAW'
            WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT < AWAY_SCORE_FT THEN 'LOSS'
            WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT > HOME_SCORE_FT THEN 'WIN'
            WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT = HOME_SCORE_FT THEN 'DRAW'
            WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT < HOME_SCORE_FT THEN 'LOSS'
            ELSE 'UNKNOWN'
        END AS FINAL_RESULT,
        IFF(GOALS_SCORED_AFTER_CONCEDING > 0, 1, 0) AS REACTED_FLAG,
        CURRENT_TIMESTAMP() AS BUILT_AT
    FROM scored;

    CREATE OR REPLACE TABLE GOLD.DIM_COMPETITION_SUMMARY AS
    SELECT COMPETITION_NAME,
        COUNT(*) AS CONCEDED_EVENTS,
        SUM(REACTED_FLAG) AS REACTED_EVENTS,
        ROUND(100.0 * SUM(REACTED_FLAG) / NULLIF(COUNT(*), 0), 2) AS PCT_REACTED,
        ROUND(AVG(GOALS_SCORED_AFTER_CONCEDING), 3) AS AVG_GOALS_AFTER_CONCEDING,
        SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) AS EVENTS_ENDED_WIN,
        SUM(IFF(FINAL_RESULT = 'DRAW', 1, 0)) AS EVENTS_ENDED_DRAW,
        SUM(IFF(FINAL_RESULT = 'LOSS', 1, 0)) AS EVENTS_ENDED_LOSS,
        ROUND(100.0 * SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) / NULLIF(COUNT(*), 0), 2) AS PCT_ENDED_WIN,
        CURRENT_TIMESTAMP() AS BUILT_AT
    FROM GOLD.FACT_REACTION_EVENTS
    GROUP BY COMPETITION_NAME;

    RETURN 'GOLD_OK fact_rows=' || (SELECT COUNT(*)::STRING FROM GOLD.FACT_REACTION_EVENTS);
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_QUALITY_CHECKS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    fail_cnt NUMBER;
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE RAW.QC_RUN_CTX AS
    SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC01', 'matches_required_fields', 'BRONZE',
           IFF(SUM(IFF(MATCH_DATE IS NULL OR TEAM_HOME IS NULL OR TEAM_AWAY IS NULL
                       OR SCORE_FT_HOME IS NULL OR SCORE_FT_AWAY IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(MATCH_DATE IS NULL OR TEAM_HOME IS NULL OR TEAM_AWAY IS NULL
                   OR SCORE_FT_HOME IS NULL OR SCORE_FT_AWAY IS NULL, 1, 0)),
           COUNT(*), 'date/teams/score'
    FROM BRONZE.MATCHES;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC02', 'matches_score_non_negative', 'BRONZE',
           IFF(SUM(IFF(TRY_TO_NUMBER(SCORE_FT_HOME) < 0 OR TRY_TO_NUMBER(SCORE_FT_AWAY) < 0, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(TRY_TO_NUMBER(SCORE_FT_HOME) < 0 OR TRY_TO_NUMBER(SCORE_FT_AWAY) < 0, 1, 0)),
           COUNT(*), 'score >= 0'
    FROM BRONZE.MATCHES;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC03', 'goal_events_fk_matches', 'SILVER',
           IFF(SUM(IFF(M.MATCH_ID IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(M.MATCH_ID IS NULL, 1, 0)), COUNT(*), 'fk matches'
    FROM SILVER.GOAL_EVENTS G
    LEFT JOIN SILVER.MATCHES M ON G.MATCH_ID = M.MATCH_ID;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC04', 'goal_minute_range', 'SILVER',
           IFF(SUM(IFF(MINUTE < 0 OR MINUTE > 130, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(MINUTE < 0 OR MINUTE > 130, 1, 0)), COUNT(*), 'minuto 0-130'
    FROM SILVER.GOAL_EVENTS;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC05', 'fact_reacted_flag_consistency', 'GOLD',
           IFF(SUM(IFF(
               (GOALS_SCORED_AFTER_CONCEDING > 0 AND REACTED_FLAG <> 1)
               OR (GOALS_SCORED_AFTER_CONCEDING = 0 AND REACTED_FLAG <> 0), 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(
               (GOALS_SCORED_AFTER_CONCEDING > 0 AND REACTED_FLAG <> 1)
               OR (GOALS_SCORED_AFTER_CONCEDING = 0 AND REACTED_FLAG <> 0), 1, 0)),
           COUNT(*), 'reacted_flag'
    FROM GOLD.FACT_REACTION_EVENTS;

    SELECT COUNT(*) INTO :fail_cnt
    FROM QC.CHECK_RESULTS
    WHERE RUN_ID = (SELECT RUN_ID FROM RAW.QC_RUN_CTX) AND STATUS = 'FAIL';

    IF (:fail_cnt > 0) THEN
        RETURN 'QC_FAIL checks_failed=' || :fail_cnt::STRING;
    END IF;
    RETURN 'QC_PASS';
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_RUN_PIPELINE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    r1 STRING;
    r2 STRING;
    r3 STRING;
    r4 STRING;
BEGIN
    CALL PIPE.SP_BRONZE_INGEST() INTO :r1;
    CALL PIPE.SP_SILVER_TRANSFORM() INTO :r2;
    CALL PIPE.SP_GOLD_BUILD() INTO :r4;
    CALL PIPE.SP_QUALITY_CHECKS() INTO :r3;

    IF (STARTSWITH(:r3, 'QC_FAIL')) THEN
        UPDATE QC.PIPELINE_RUNS
        SET STATUS = 'QC_FAIL', FINISHED_AT = CURRENT_TIMESTAMP(),
            NOTES = :r1 || ' | ' || :r2 || ' | ' || :r3 || ' | ' || :r4
        WHERE STARTED_AT = (SELECT MAX(STARTED_AT) FROM QC.PIPELINE_RUNS);
        RETURN 'PIPELINE_QC_FAIL ' || :r3;
    END IF;

    UPDATE QC.PIPELINE_RUNS
    SET STATUS = 'SUCCESS',
        FINISHED_AT = CURRENT_TIMESTAMP(),
        SILVER_ROWS = (SELECT COUNT(*) FROM SILVER.MATCHES),
        QUARANTINE_ROWS = (SELECT COUNT(*) FROM SILVER.MATCHES_QUARANTINE)
            + (SELECT COUNT(*) FROM SILVER.GOAL_EVENTS_QUARANTINE),
        NOTES = :r1 || ' | ' || :r2 || ' | ' || :r3 || ' | ' || :r4
    WHERE STARTED_AT = (SELECT MAX(STARTED_AT) FROM QC.PIPELINE_RUNS);

    RETURN 'PIPELINE_SUCCESS ' || :r1 || ' | ' || :r2 || ' | ' || :r3 || ' | ' || :r4;
END;
$$;

-- Janela operacional: fora de Copa = semanal; em ano de Copa = diario (mesmo criterio Databricks)
ALTER TASK IF EXISTS PIPE.TASK_OPENFOOTBALL_WEEKLY SUSPEND;
DROP TASK IF EXISTS PIPE.TASK_OPENFOOTBALL_WEEKLY;
ALTER TASK IF EXISTS PIPE.TASK_OPENFOOTBALL_DAILY SUSPEND;
DROP TASK IF EXISTS PIPE.TASK_OPENFOOTBALL_DAILY;
ALTER TASK IF EXISTS PIPE.TASK_WORLDCUP_WEEKLY SUSPEND;
DROP TASK IF EXISTS PIPE.TASK_WORLDCUP_WEEKLY;

CREATE OR REPLACE TASK PIPE.TASK_WORLDCUP_WEEKLY
    WAREHOUSE = WH_DI_P_PIPELINE
    SCHEDULE = 'USING CRON 0 6 * * 1 America/Sao_Paulo'
    COMMENT = 'World Cup pipeline semanal (segunda 06:00 America/Sao_Paulo)'
AS
    CALL PIPE.SP_RUN_PIPELINE();

ALTER TASK PIPE.TASK_WORLDCUP_WEEKLY RESUME;

DELETE FROM QC.PIPELINE_SCHEDULE;

INSERT INTO QC.PIPELINE_SCHEDULE (
    SCHEDULE_NAME, CRON_EXPR, TIMEZONE, FREQUENCY_DESC, JUSTIFICATION, TASK_NAME
)
VALUES
(
    'worldcup_weekly_default',
    '0 6 * * 1',
    'America/Sao_Paulo',
    'Semanal (segunda 06:00) - padrao fora do torneio',
    'Extracao full do ZIP worldcup.json. Fora de ano de Copa nao ha jogos novos; cadencia semanal reduz custo.',
    'PIPE.TASK_WORLDCUP_WEEKLY'
),
(
    'worldcup_daily_tournament_opcional',
    '0 6 * * *',
    'America/Sao_Paulo',
    'Diario (06:00) - opcional em ano de Copa',
    'Padrao ativo e semanal. Em ano de Copa, o operador pode alterar o SCHEDULE da TASK_WORLDCUP_WEEKLY para CRON diario.',
    'PIPE.TASK_WORLDCUP_WEEKLY'
);

SHOW TASKS IN SCHEMA DI_P_MEDALLION.PIPE;
SELECT * FROM QC.PIPELINE_SCHEDULE;
