USE ROLE ACCOUNTADMIN;
USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;
USE SCHEMA PIPE;

CREATE SCHEMA IF NOT EXISTS PIPE COMMENT = 'Procedures e tasks do pipeline';

CREATE OR REPLACE PROCEDURE PIPE.SP_BRONZE_INGEST()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE RAW.RUN_CTX AS
    SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

    INSERT INTO QC.PIPELINE_RUNS (RUN_ID, STATUS, SOURCE_FILE, NOTES)
    SELECT RUN_ID, 'RUNNING', 'stage:@RAW.STG_OPENFOOTBALL', 'Inicio Bronze MATCHES_RAW/GOALS_RAW'
    FROM RAW.RUN_CTX;

    CREATE OR REPLACE TABLE BRONZE.MATCHES_RAW (
        MATCH_ID STRING, SEASON STRING, LEAGUE_CODE STRING, LEAGUE_NAME STRING, MATCHDAY STRING,
        MATCH_DATE STRING, MATCH_TIME STRING, HOME_TEAM STRING, AWAY_TEAM STRING,
        HOME_SCORE_HT STRING, AWAY_SCORE_HT STRING, HOME_SCORE_FT STRING, AWAY_SCORE_FT STRING,
        SOURCE_FILE STRING, SOURCE_REPO STRING, HAS_GOAL_EVENTS STRING,
        _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _RUN_ID STRING
    );

    CREATE OR REPLACE TABLE BRONZE.GOALS_RAW (
        MATCH_ID STRING, SEASON STRING, LEAGUE_CODE STRING, LEAGUE_NAME STRING,
        MATCH_DATE STRING, MATCH_DATE_RAW STRING, HOME_TEAM STRING, AWAY_TEAM STRING,
        HOME_SCORE_FT STRING, AWAY_SCORE_FT STRING, TEAM STRING, OPPONENT STRING,
        SCORER STRING, MINUTE STRING, MINUTE_RAW STRING, IS_PENALTY STRING, IS_OWN_GOAL STRING,
        EVENT_SEQ STRING, SOURCE_FILE STRING, SOURCE_REPO STRING,
        _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _RUN_ID STRING
    );

    CREATE OR REPLACE TABLE BRONZE.LEAGUE_CATALOG (
        LEAGUE_CODE STRING, LEAGUE_NAME STRING, SEASON STRING, SOURCE_FILE STRING,
        _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _RUN_ID STRING
    );

    COPY INTO BRONZE.MATCHES_RAW (
        MATCH_ID, SEASON, LEAGUE_CODE, LEAGUE_NAME, MATCHDAY, MATCH_DATE, MATCH_TIME,
        HOME_TEAM, AWAY_TEAM, HOME_SCORE_HT, AWAY_SCORE_HT, HOME_SCORE_FT, AWAY_SCORE_FT,
        SOURCE_FILE, SOURCE_REPO, HAS_GOAL_EVENTS
    )
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16
        FROM @RAW.STG_OPENFOOTBALL/matches_bronze.csv
    )
    FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_OPENFOOTBALL')
    ON_ERROR = 'CONTINUE';

    COPY INTO BRONZE.GOALS_RAW (
        MATCH_ID, SEASON, LEAGUE_CODE, LEAGUE_NAME, MATCH_DATE, MATCH_DATE_RAW,
        HOME_TEAM, AWAY_TEAM, HOME_SCORE_FT, AWAY_SCORE_FT,
        TEAM, OPPONENT, SCORER, MINUTE, MINUTE_RAW, IS_PENALTY, IS_OWN_GOAL, EVENT_SEQ,
        SOURCE_FILE, SOURCE_REPO
    )
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20
        FROM @RAW.STG_OPENFOOTBALL/goals_bronze.csv
    )
    FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_OPENFOOTBALL')
    ON_ERROR = 'CONTINUE';

    COPY INTO BRONZE.LEAGUE_CATALOG (LEAGUE_CODE, LEAGUE_NAME, SEASON, SOURCE_FILE)
    FROM (
        SELECT $1,$2,$3,$4 FROM @RAW.STG_OPENFOOTBALL/league_catalog.csv
    )
    FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV_OPENFOOTBALL')
    ON_ERROR = 'CONTINUE';

    UPDATE BRONZE.MATCHES_RAW SET _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX) WHERE _RUN_ID IS NULL;
    UPDATE BRONZE.GOALS_RAW SET _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX) WHERE _RUN_ID IS NULL;
    UPDATE BRONZE.LEAGUE_CATALOG SET _RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX) WHERE _RUN_ID IS NULL;

    UPDATE QC.PIPELINE_RUNS R
    SET BRONZE_ROWS = (SELECT COUNT(*) FROM BRONZE.MATCHES_RAW),
        STATUS = 'BRONZE_OK',
        NOTES = 'MATCHES_RAW + GOALS_RAW'
    WHERE R.RUN_ID = (SELECT RUN_ID FROM RAW.RUN_CTX);

    RETURN 'BRONZE_OK rows=' || (SELECT COUNT(*)::STRING FROM BRONZE.MATCHES_RAW);
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_SILVER_TRANSFORM()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TABLE SILVER.MATCHES_QUARANTINE AS
    SELECT MATCH_ID, SEASON, LEAGUE_CODE, HOME_TEAM, AWAY_TEAM, HOME_SCORE_FT, AWAY_SCORE_FT,
           'INVALID_MATCH' AS QUARANTINE_REASON, CURRENT_TIMESTAMP() AS QUARANTINED_AT
    FROM BRONZE.MATCHES_RAW
    WHERE MATCH_ID IS NULL OR MATCH_DATE IS NULL OR HOME_TEAM IS NULL OR AWAY_TEAM IS NULL
       OR TRY_TO_NUMBER(HOME_SCORE_FT) IS NULL OR TRY_TO_NUMBER(AWAY_SCORE_FT) IS NULL
       OR TRY_TO_NUMBER(HOME_SCORE_FT) < 0 OR TRY_TO_NUMBER(AWAY_SCORE_FT) < 0
       OR UPPER(TRIM(HOME_TEAM)) = UPPER(TRIM(AWAY_TEAM));

    CREATE OR REPLACE TABLE SILVER.MATCHES AS
    SELECT
        MATCH_ID, SEASON, LEAGUE_CODE, LEAGUE_NAME, MATCHDAY,
        TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE, MATCH_TIME,
        TRIM(HOME_TEAM) AS HOME_TEAM, TRIM(AWAY_TEAM) AS AWAY_TEAM,
        TRY_TO_NUMBER(HOME_SCORE_HT) AS HOME_SCORE_HT,
        TRY_TO_NUMBER(AWAY_SCORE_HT) AS AWAY_SCORE_HT,
        TRY_TO_NUMBER(HOME_SCORE_FT) AS HOME_SCORE_FT,
        TRY_TO_NUMBER(AWAY_SCORE_FT) AS AWAY_SCORE_FT,
        SOURCE_FILE, SOURCE_REPO,
        TRY_TO_NUMBER(HAS_GOAL_EVENTS) AS HAS_GOAL_EVENTS,
        _INGESTED_AT, _RUN_ID
    FROM BRONZE.MATCHES_RAW
    WHERE MATCH_ID IS NOT NULL AND MATCH_DATE IS NOT NULL
      AND HOME_TEAM IS NOT NULL AND AWAY_TEAM IS NOT NULL
      AND TRY_TO_NUMBER(HOME_SCORE_FT) IS NOT NULL AND TRY_TO_NUMBER(AWAY_SCORE_FT) IS NOT NULL
      AND TRY_TO_NUMBER(HOME_SCORE_FT) >= 0 AND TRY_TO_NUMBER(AWAY_SCORE_FT) >= 0
      AND UPPER(TRIM(HOME_TEAM)) <> UPPER(TRIM(AWAY_TEAM));

    CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS_QUARANTINE AS
    SELECT MATCH_ID, TEAM, SCORER, MINUTE, 'INVALID_GOAL_EVENT' AS QUARANTINE_REASON,
           CURRENT_TIMESTAMP() AS QUARANTINED_AT
    FROM BRONZE.GOALS_RAW
    WHERE MATCH_ID IS NULL OR TEAM IS NULL OR SCORER IS NULL
       OR TRY_TO_NUMBER(MINUTE) IS NULL OR TRY_TO_NUMBER(MINUTE) < 0 OR TRY_TO_NUMBER(MINUTE) > 130;

    CREATE OR REPLACE TABLE SILVER.GOAL_EVENTS AS
    SELECT
        G.MATCH_ID, G.SEASON, G.LEAGUE_CODE, G.LEAGUE_NAME,
        TRY_TO_DATE(G.MATCH_DATE) AS MATCH_DATE,
        TRIM(G.HOME_TEAM) AS HOME_TEAM, TRIM(G.AWAY_TEAM) AS AWAY_TEAM,
        TRY_TO_NUMBER(G.HOME_SCORE_FT) AS HOME_SCORE_FT,
        TRY_TO_NUMBER(G.AWAY_SCORE_FT) AS AWAY_SCORE_FT,
        TRIM(G.TEAM) AS TEAM, TRIM(G.OPPONENT) AS OPPONENT, TRIM(G.SCORER) AS SCORER,
        TRY_TO_NUMBER(G.MINUTE)::NUMBER(38,0) AS MINUTE, G.MINUTE_RAW,
        TRY_TO_NUMBER(G.IS_PENALTY)::NUMBER(38,0) AS IS_PENALTY,
        TRY_TO_NUMBER(G.IS_OWN_GOAL)::NUMBER(38,0) AS IS_OWN_GOAL,
        TRY_TO_NUMBER(G.EVENT_SEQ)::NUMBER(38,0) AS EVENT_SEQ,
        CASE WHEN TRY_TO_NUMBER(G.IS_OWN_GOAL) = 1 THEN TRIM(G.OPPONENT) ELSE TRIM(G.TEAM) END AS CREDITED_TEAM,
        CASE WHEN TRY_TO_NUMBER(G.IS_OWN_GOAL) = 1 THEN TRIM(G.TEAM) ELSE TRIM(G.OPPONENT) END AS CONCEDING_TEAM,
        G.SOURCE_FILE, G.SOURCE_REPO, G._INGESTED_AT, G._RUN_ID
    FROM BRONZE.GOALS_RAW G
    WHERE G.MATCH_ID IS NOT NULL AND G.TEAM IS NOT NULL AND G.SCORER IS NOT NULL
      AND TRY_TO_NUMBER(G.MINUTE) IS NOT NULL
      AND TRY_TO_NUMBER(G.MINUTE) >= 0 AND TRY_TO_NUMBER(G.MINUTE) <= 130;

    RETURN 'SILVER_OK matches=' || (SELECT COUNT(*)::STRING FROM SILVER.MATCHES)
        || ' goals=' || (SELECT COUNT(*)::STRING FROM SILVER.GOAL_EVENTS);
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_GOLD_BUILD()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE OR REPLACE TABLE GOLD.RESPONSE_AFTER_CONCEDING AS
    WITH ordered AS (
        SELECT
            E.MATCH_ID, E.LEAGUE_CODE AS LEAGUE, E.SEASON, E.MATCH_DATE,
            E.HOME_TEAM, E.AWAY_TEAM, E.HOME_SCORE_FT, E.AWAY_SCORE_FT,
            E.SCORER, E.MINUTE AS GOAL_MINUTE, E.EVENT_SEQ,
            E.IS_PENALTY, E.IS_OWN_GOAL, E.CREDITED_TEAM, E.CONCEDING_TEAM
        FROM SILVER.GOAL_EVENTS E
    ),
    scored AS (
        SELECT
            O.*,
            (SELECT COUNT(*) FROM ordered P
             WHERE P.MATCH_ID = O.MATCH_ID
               AND (P.GOAL_MINUTE < O.GOAL_MINUTE
                    OR (P.GOAL_MINUTE = O.GOAL_MINUTE AND P.EVENT_SEQ < O.EVENT_SEQ))
               AND P.CREDITED_TEAM = O.HOME_TEAM) AS HOME_GOALS_BEFORE,
            (SELECT COUNT(*) FROM ordered P
             WHERE P.MATCH_ID = O.MATCH_ID
               AND (P.GOAL_MINUTE < O.GOAL_MINUTE
                    OR (P.GOAL_MINUTE = O.GOAL_MINUTE AND P.EVENT_SEQ < O.EVENT_SEQ))
               AND P.CREDITED_TEAM = O.AWAY_TEAM) AS AWAY_GOALS_BEFORE,
            (SELECT COUNT(*) FROM ordered AFT
             WHERE AFT.MATCH_ID = O.MATCH_ID
               AND AFT.CREDITED_TEAM = O.CONCEDING_TEAM
               AND (AFT.GOAL_MINUTE > O.GOAL_MINUTE
                    OR (AFT.GOAL_MINUTE = O.GOAL_MINUTE AND AFT.EVENT_SEQ > O.EVENT_SEQ))
            ) AS GOALS_SCORED_AFTER_CONCEDING
        FROM ordered O
    )
    SELECT
        MATCH_ID, LEAGUE, SEASON, MATCH_DATE, HOME_TEAM, AWAY_TEAM,
        CONCEDING_TEAM, CREDITED_TEAM AS SCORING_TEAM, SCORER, GOAL_MINUTE, EVENT_SEQ,
        IS_PENALTY, IS_OWN_GOAL,
        CASE WHEN CONCEDING_TEAM = HOME_TEAM THEN HOME_GOALS_BEFORE - AWAY_GOALS_BEFORE
             ELSE AWAY_GOALS_BEFORE - HOME_GOALS_BEFORE END AS SCORE_DIFF_BEFORE_GOAL,
        GOALS_SCORED_AFTER_CONCEDING,
        CASE
            WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT > AWAY_SCORE_FT THEN 'WIN'
            WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT = AWAY_SCORE_FT THEN 'DRAW'
            WHEN CONCEDING_TEAM = HOME_TEAM AND HOME_SCORE_FT < AWAY_SCORE_FT THEN 'LOSS'
            WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT > HOME_SCORE_FT THEN 'WIN'
            WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT = HOME_SCORE_FT THEN 'DRAW'
            WHEN CONCEDING_TEAM = AWAY_TEAM AND AWAY_SCORE_FT < HOME_SCORE_FT THEN 'LOSS'
            ELSE 'UNKNOWN'
        END AS FINAL_RESULT,
        IFF(GOALS_SCORED_AFTER_CONCEDING > 0, 1, 0) AS REACTED_FLAG,
        CURRENT_TIMESTAMP() AS BUILT_AT
    FROM scored;

    CREATE OR REPLACE TABLE GOLD.LEAGUE_REACTION_SUMMARY AS
    SELECT
        LEAGUE, SEASON,
        COUNT(*) AS CONCEDED_EVENTS,
        SUM(REACTED_FLAG) AS REACTED_EVENTS,
        ROUND(100.0 * SUM(REACTED_FLAG) / NULLIF(COUNT(*), 0), 2) AS PCT_REACTED,
        ROUND(AVG(GOALS_SCORED_AFTER_CONCEDING), 3) AS AVG_GOALS_AFTER_CONCEDING,
        SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) AS EVENTS_ENDED_WIN,
        SUM(IFF(FINAL_RESULT = 'DRAW', 1, 0)) AS EVENTS_ENDED_DRAW,
        SUM(IFF(FINAL_RESULT = 'LOSS', 1, 0)) AS EVENTS_ENDED_LOSS,
        ROUND(100.0 * SUM(IFF(FINAL_RESULT = 'WIN', 1, 0)) / NULLIF(COUNT(*), 0), 2) AS PCT_ENDED_WIN,
        CURRENT_TIMESTAMP() AS BUILT_AT
    FROM GOLD.RESPONSE_AFTER_CONCEDING
    GROUP BY LEAGUE, SEASON;

    RETURN 'GOLD_OK reaction_rows=' || (SELECT COUNT(*)::STRING FROM GOLD.RESPONSE_AFTER_CONCEDING);
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_QUALITY_CHECKS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_run_id STRING;
    v_fail NUMBER;
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE RAW.QC_RUN_CTX AS
    SELECT TO_VARCHAR(UUID_STRING()) AS RUN_ID;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC01', 'matches_required_fields', 'BRONZE',
           IFF(SUM(IFF(MATCH_DATE IS NULL OR HOME_TEAM IS NULL OR AWAY_TEAM IS NULL
                       OR HOME_SCORE_FT IS NULL OR AWAY_SCORE_FT IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(MATCH_DATE IS NULL OR HOME_TEAM IS NULL OR AWAY_TEAM IS NULL
                   OR HOME_SCORE_FT IS NULL OR AWAY_SCORE_FT IS NULL, 1, 0)),
           COUNT(*), 'campos obrigatorios'
    FROM BRONZE.MATCHES_RAW;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC02', 'matches_score_non_negative', 'BRONZE',
           IFF(SUM(IFF(TRY_TO_NUMBER(HOME_SCORE_FT) < 0 OR TRY_TO_NUMBER(AWAY_SCORE_FT) < 0, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(TRY_TO_NUMBER(HOME_SCORE_FT) < 0 OR TRY_TO_NUMBER(AWAY_SCORE_FT) < 0, 1, 0)),
           COUNT(*), 'score >= 0'
    FROM BRONZE.MATCHES_RAW;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC03', 'goal_event_has_valid_match_id', 'SILVER',
           IFF(SUM(IFF(M.MATCH_ID IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(M.MATCH_ID IS NULL, 1, 0)), COUNT(*), 'FK match_id'
    FROM SILVER.GOAL_EVENTS G
    LEFT JOIN SILVER.MATCHES M ON G.MATCH_ID = M.MATCH_ID;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC04', 'matches_unique_natural_key', 'SILVER',
           IFF(COUNT(*) = COUNT(DISTINCT MATCH_ID), 'PASS', 'FAIL'),
           COUNT(*) - COUNT(DISTINCT MATCH_ID), COUNT(*), 'match_id unico'
    FROM SILVER.MATCHES;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC05', 'goal_events_minute_sane', 'SILVER',
           IFF(SUM(IFF(MINUTE < 0 OR MINUTE > 130 OR SCORER IS NULL, 1, 0)) = 0, 'PASS', 'FAIL'),
           SUM(IFF(MINUTE < 0 OR MINUTE > 130 OR SCORER IS NULL, 1, 0)), COUNT(*), 'minuto/scorer'
    FROM SILVER.GOAL_EVENTS;

    INSERT INTO QC.CHECK_RESULTS (RUN_ID, CHECK_ID, CHECK_NAME, LAYER, STATUS, FAILED_ROWS, TOTAL_ROWS, DETAILS)
    SELECT (SELECT RUN_ID FROM RAW.QC_RUN_CTX), 'QC06', 'gold_has_reaction_rows', 'GOLD',
           IFF(COUNT(*) > 0, 'PASS', 'FAIL'), IFF(COUNT(*) > 0, 0, 1), COUNT(*), 'gold populada'
    FROM GOLD.RESPONSE_AFTER_CONCEDING;

    SELECT RUN_ID INTO :v_run_id FROM RAW.QC_RUN_CTX;
    SELECT COUNT(*) INTO :v_fail FROM QC.CHECK_RESULTS
    WHERE RUN_ID = :v_run_id AND STATUS = 'FAIL';

    IF (:v_fail > 0) THEN
        RETURN 'QC_FAIL run_id=' || :v_run_id || ' fails=' || :v_fail::STRING;
    END IF;
    RETURN 'QC_PASS run_id=' || :v_run_id;
END;
$$;

CREATE OR REPLACE PROCEDURE PIPE.SP_RUN_PIPELINE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    r1 STRING;
    r2 STRING;
    r3 STRING;
    r4 STRING;
BEGIN
    CALL PIPE.SP_BRONZE_INGEST() INTO :r1;
    CALL PIPE.SP_SILVER_TRANSFORM() INTO :r2;
    CALL PIPE.SP_GOLD_BUILD() INTO :r4;
    CALL PIPE.SP_QUALITY_CHECKS() INTO :r3;

    IF (STARTSWITH(:r3, 'QC_FAIL')) THEN
        UPDATE QC.PIPELINE_RUNS
        SET STATUS = 'QC_FAIL', FINISHED_AT = CURRENT_TIMESTAMP(),
            NOTES = :r1 || ' | ' || :r2 || ' | ' || :r3 || ' | ' || :r4
        WHERE STARTED_AT = (SELECT MAX(STARTED_AT) FROM QC.PIPELINE_RUNS);
        RETURN 'PIPELINE_QC_FAIL ' || :r3;
    END IF;

    UPDATE QC.PIPELINE_RUNS
    SET STATUS = 'SUCCESS',
        FINISHED_AT = CURRENT_TIMESTAMP(),
        SILVER_ROWS = (SELECT COUNT(*) FROM SILVER.MATCHES),
        QUARANTINE_ROWS = (SELECT COUNT(*) FROM SILVER.MATCHES_QUARANTINE)
            + (SELECT COUNT(*) FROM SILVER.GOAL_EVENTS_QUARANTINE),
        NOTES = :r1 || ' | ' || :r2 || ' | ' || :r3 || ' | ' || :r4
    WHERE STARTED_AT = (SELECT MAX(STARTED_AT) FROM QC.PIPELINE_RUNS);

    RETURN 'PIPELINE_SUCCESS ' || :r1 || ' | ' || :r2 || ' | ' || :r3 || ' | ' || :r4;
END;
$$;

-- Schedule semanal: segunda 06:00 America/Sao_Paulo
ALTER TASK IF EXISTS PIPE.TASK_OPENFOOTBALL_DAILY SUSPEND;
DROP TASK IF EXISTS PIPE.TASK_OPENFOOTBALL_DAILY;

CREATE OR REPLACE TASK PIPE.TASK_OPENFOOTBALL_WEEKLY
    WAREHOUSE = WH_DI_P_PIPELINE
    SCHEDULE = 'USING CRON 0 6 * * 1 America/Sao_Paulo'
    COMMENT = 'Pipeline openfootball semanal: segunda 06:00 America/Sao_Paulo'
AS
    CALL PIPE.SP_RUN_PIPELINE();

ALTER TASK PIPE.TASK_OPENFOOTBALL_WEEKLY RESUME;

DELETE FROM QC.PIPELINE_SCHEDULE;

INSERT INTO QC.PIPELINE_SCHEDULE (
    SCHEDULE_NAME, CRON_EXPR, TIMEZONE, FREQUENCY_DESC, JUSTIFICATION, TASK_NAME
)
VALUES (
    'openfootball_weekly',
    '0 6 * * 1',
    'America/Sao_Paulo',
    'Semanal (toda segunda as 06:00)',
    'Rodadas europeias fecham no domingo; analise de reacao pos-gol e retrospectiva. Cadencia semanal evita custo sem dado novo (GOVERNANCE).',
    'PIPE.TASK_OPENFOOTBALL_WEEKLY'
);

SHOW TASKS IN SCHEMA DI_P_MEDALLION.PIPE;
SELECT * FROM QC.PIPELINE_SCHEDULE;
