USE ROLE ACCOUNTADMIN;
USE DATABASE DI_P_MEDALLION;
USE WAREHOUSE WH_DI_P_PIPELINE;
USE SCHEMA GOLD;

CREATE STAGE IF NOT EXISTS GOLD.STG_STREAMLIT_APP;

CREATE OR REPLACE STREAMLIT GOLD.WORLDCUP_GOLD_DASH
    ROOT_LOCATION = '@DI_P_MEDALLION.GOLD.STG_STREAMLIT_APP'
    MAIN_FILE = '/streamlit_app.py'
    QUERY_WAREHOUSE = WH_DI_P_PIPELINE
    TITLE = 'World Cup Gold Insights'
    COMMENT = 'Dashboard Gold FACT_REACTION_EVENTS';

DROP STREAMLIT IF EXISTS GOLD.OPENFOOTBALL_GOLD_DASH;
