{{ config(alias='goal_events') }}

SELECT
    MATCH_ID,
    COMPETITION_NAME,
    TRY_CAST(MATCH_DATE AS DATE) AS MATCH_DATE,
    TRIM(TEAM_HOME) AS HOME_TEAM,
    TRIM(TEAM_AWAY) AS AWAY_TEAM,
    TRY_CAST(SCORE_FT_HOME AS INT) AS HOME_SCORE_FT,
    TRY_CAST(SCORE_FT_AWAY AS INT) AS AWAY_SCORE_FT,
    TRIM(TEAM) AS TEAM,
    TRIM(OPPONENT) AS OPPONENT,
    TRIM(SCORER) AS SCORER,
    TRY_CAST(MINUTE AS INT) AS MINUTE,
    TRY_CAST(IS_PENALTY AS INT) AS IS_PENALTY,
    TRY_CAST(IS_OWN_GOAL AS INT) AS IS_OWN_GOAL,
    TRY_CAST(EVENT_SEQ AS INT) AS EVENT_SEQ,
    TRIM(TEAM) AS CREDITED_TEAM,
    TRIM(OPPONENT) AS CONCEDING_TEAM,
    SOURCE_FILE,
    INGESTED_AT
FROM {{ source('bronze', 'goals_raw') }}
WHERE MATCH_ID IS NOT NULL
  AND TEAM IS NOT NULL
  AND SCORER IS NOT NULL
  AND TRY_CAST(MINUTE AS INT) IS NOT NULL
  AND TRY_CAST(MINUTE AS INT) >= 0
  AND TRY_CAST(MINUTE AS INT) <= 130
