{{ config(alias='goal_events_quarantine') }}

SELECT
    MATCH_ID,
    COMPETITION_NAME,
    MATCH_DATE,
    TEAM_HOME,
    TEAM_AWAY,
    TEAM,
    OPPONENT,
    SCORER,
    MINUTE,
    SOURCE_FILE,
    'EVENTO_GOL_INVALIDO' AS QUARANTINE_REASON
FROM {{ ref('stg_goals') }}
WHERE MATCH_ID IS NULL
   OR TEAM IS NULL
   OR SCORER IS NULL
   OR TRY_TO_NUMBER(MINUTE) IS NULL
   OR TRY_TO_NUMBER(MINUTE) < 0
   OR TRY_TO_NUMBER(MINUTE) > 130
