{{ config(alias='goal_events') }}

SELECT
    MATCH_ID,
    COMPETITION_NAME,
    TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE,
    TRIM(TEAM_HOME) AS HOME_TEAM,
    TRIM(TEAM_AWAY) AS AWAY_TEAM,
    TRY_TO_NUMBER(SCORE_FT_HOME) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(SCORE_FT_AWAY) AS AWAY_SCORE_FT,
    TRIM(TEAM) AS TEAM,
    TRIM(OPPONENT) AS OPPONENT,
    TRIM(SCORER) AS SCORER,
    TRY_TO_NUMBER(MINUTE)::NUMBER(38, 0) AS MINUTE,
    TRY_TO_NUMBER(IS_PENALTY)::NUMBER(38, 0) AS IS_PENALTY,
    TRY_TO_NUMBER(IS_OWN_GOAL)::NUMBER(38, 0) AS IS_OWN_GOAL,
    TRY_TO_NUMBER(EVENT_SEQ)::NUMBER(38, 0) AS EVENT_SEQ,
    TRIM(TEAM) AS CREDITED_TEAM,
    TRIM(OPPONENT) AS CONCEDING_TEAM,
    SOURCE_FILE,
    INGESTED_AT
FROM {{ ref('stg_goals') }}
WHERE MATCH_ID IS NOT NULL
  AND TEAM IS NOT NULL
  AND SCORER IS NOT NULL
  AND TRY_TO_NUMBER(MINUTE) IS NOT NULL
  AND TRY_TO_NUMBER(MINUTE) >= 0
  AND TRY_TO_NUMBER(MINUTE) <= 130
