{{ config(alias='matches_quarantine') }}

SELECT
    MATCH_ID,
    COMPETITION_NAME,
    ROUND,
    MATCH_DATE,
    MATCH_TIME,
    TEAM_HOME,
    TEAM_AWAY,
    SCORE_FT_HOME,
    SCORE_FT_AWAY,
    SOURCE_FILE,
    'PARTIDA_INVALIDA' AS QUARANTINE_REASON
FROM {{ ref('stg_matches') }}
WHERE MATCH_ID IS NULL
   OR MATCH_DATE IS NULL
   OR TEAM_HOME IS NULL
   OR TEAM_AWAY IS NULL
   OR TRY_TO_NUMBER(SCORE_FT_HOME) IS NULL
   OR TRY_TO_NUMBER(SCORE_FT_AWAY) IS NULL
   OR TRY_TO_NUMBER(SCORE_FT_HOME) < 0
   OR TRY_TO_NUMBER(SCORE_FT_AWAY) < 0
   OR UPPER(TRIM(TEAM_HOME)) = UPPER(TRIM(TEAM_AWAY))
