{{ config(alias='matches') }}

SELECT
    MATCH_ID,
    COMPETITION_NAME,
    ROUND AS MATCHDAY,
    TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE,
    MATCH_TIME,
    TRIM(TEAM_HOME) AS HOME_TEAM,
    TRIM(TEAM_AWAY) AS AWAY_TEAM,
    TRY_TO_NUMBER(SCORE_HT_HOME) AS HOME_SCORE_HT,
    TRY_TO_NUMBER(SCORE_HT_AWAY) AS AWAY_SCORE_HT,
    TRY_TO_NUMBER(SCORE_FT_HOME) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(SCORE_FT_AWAY) AS AWAY_SCORE_FT,
    SOURCE_FILE,
    INGESTED_AT
FROM {{ ref('stg_matches') }}
WHERE MATCH_ID IS NOT NULL
  AND MATCH_DATE IS NOT NULL
  AND TEAM_HOME IS NOT NULL
  AND TEAM_AWAY IS NOT NULL
  AND TRY_TO_NUMBER(SCORE_FT_HOME) IS NOT NULL
  AND TRY_TO_NUMBER(SCORE_FT_AWAY) IS NOT NULL
  AND TRY_TO_NUMBER(SCORE_FT_HOME) >= 0
  AND TRY_TO_NUMBER(SCORE_FT_AWAY) >= 0
  AND UPPER(TRIM(TEAM_HOME)) <> UPPER(TRIM(TEAM_AWAY))
