SELECT
    MATCH_ID,
    SEASON,
    LEAGUE_CODE,
    LEAGUE_NAME,
    HOME_TEAM,
    AWAY_TEAM,
    HOME_SCORE_FT,
    AWAY_SCORE_FT,
    'INVALID_MATCH' AS QUARANTINE_REASON
FROM {{ ref('stg_matches') }}
WHERE MATCH_ID IS NULL
   OR MATCH_DATE IS NULL
   OR HOME_TEAM IS NULL
   OR AWAY_TEAM IS NULL
   OR TRY_TO_NUMBER(HOME_SCORE_FT) IS NULL
   OR TRY_TO_NUMBER(AWAY_SCORE_FT) IS NULL
   OR TRY_TO_NUMBER(HOME_SCORE_FT) < 0
   OR TRY_TO_NUMBER(AWAY_SCORE_FT) < 0
   OR UPPER(TRIM(HOME_TEAM)) = UPPER(TRIM(AWAY_TEAM))
