SELECT
    MATCH_ID,
    SEASON,
    LEAGUE_CODE,
    LEAGUE_NAME,
    MATCHDAY,
    TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE,
    MATCH_TIME,
    TRIM(HOME_TEAM) AS HOME_TEAM,
    TRIM(AWAY_TEAM) AS AWAY_TEAM,
    TRY_TO_NUMBER(HOME_SCORE_HT) AS HOME_SCORE_HT,
    TRY_TO_NUMBER(AWAY_SCORE_HT) AS AWAY_SCORE_HT,
    TRY_TO_NUMBER(HOME_SCORE_FT) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(AWAY_SCORE_FT) AS AWAY_SCORE_FT,
    SOURCE_FILE,
    SOURCE_REPO,
    TRY_TO_NUMBER(HAS_GOAL_EVENTS) AS HAS_GOAL_EVENTS
FROM {{ ref('stg_matches') }}
WHERE MATCH_ID IS NOT NULL
  AND MATCH_DATE IS NOT NULL
  AND HOME_TEAM IS NOT NULL
  AND AWAY_TEAM IS NOT NULL
  AND TRY_TO_NUMBER(HOME_SCORE_FT) IS NOT NULL
  AND TRY_TO_NUMBER(AWAY_SCORE_FT) IS NOT NULL
  AND TRY_TO_NUMBER(HOME_SCORE_FT) >= 0
  AND TRY_TO_NUMBER(AWAY_SCORE_FT) >= 0
  AND UPPER(TRIM(HOME_TEAM)) <> UPPER(TRIM(AWAY_TEAM))
