SELECT
    MATCH_ID,
    SEASON,
    LEAGUE_CODE,
    LEAGUE_NAME,
    TRY_TO_DATE(MATCH_DATE) AS MATCH_DATE,
    TRIM(HOME_TEAM) AS HOME_TEAM,
    TRIM(AWAY_TEAM) AS AWAY_TEAM,
    TRY_TO_NUMBER(HOME_SCORE_FT) AS HOME_SCORE_FT,
    TRY_TO_NUMBER(AWAY_SCORE_FT) AS AWAY_SCORE_FT,
    TRIM(TEAM) AS TEAM,
    TRIM(OPPONENT) AS OPPONENT,
    TRIM(SCORER) AS SCORER,
    TRY_TO_NUMBER(MINUTE)::NUMBER(38, 0) AS MINUTE,
    MINUTE_RAW,
    TRY_TO_NUMBER(IS_PENALTY)::NUMBER(38, 0) AS IS_PENALTY,
    TRY_TO_NUMBER(IS_OWN_GOAL)::NUMBER(38, 0) AS IS_OWN_GOAL,
    TRY_TO_NUMBER(EVENT_SEQ)::NUMBER(38, 0) AS EVENT_SEQ,
    CASE
        WHEN TRY_TO_NUMBER(IS_OWN_GOAL) = 1 THEN TRIM(OPPONENT)
        ELSE TRIM(TEAM)
    END AS CREDITED_TEAM,
    CASE
        WHEN TRY_TO_NUMBER(IS_OWN_GOAL) = 1 THEN TRIM(TEAM)
        ELSE TRIM(OPPONENT)
    END AS CONCEDING_TEAM,
    SOURCE_FILE,
    SOURCE_REPO
FROM {{ ref('stg_goals') }}
WHERE MATCH_ID IS NOT NULL
  AND TEAM IS NOT NULL
  AND SCORER IS NOT NULL
  AND TRY_TO_NUMBER(MINUTE) IS NOT NULL
  AND TRY_TO_NUMBER(MINUTE) >= 0
  AND TRY_TO_NUMBER(MINUTE) <= 130
